# hardware-configuration.nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  swapDevices = [];

  # networking.useDHCP = lib.mkDefault false;

  powerManagement.cpuFreqGovernor = "ondemand";
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
