# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["tcp_bbr" "kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/11cd85fd-8feb-4d09-96c6-a822676d1124";
      fsType = "btrfs";
      options = ["compress-force=zstd" "noatime" "subvol=@/root"];
    };

    "/persist" = {
      device = "/dev/disk/by-uuid/11cd85fd-8feb-4d09-96c6-a822676d1124";
      fsType = "btrfs";
      options = ["compress-force=zstd" "noatime" "subvol=@/persist"];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/11cd85fd-8feb-4d09-96c6-a822676d1124";
      fsType = "btrfs";
      options = ["compress-force=zstd" "noatime" "subvol=@/nix"];
    };

    "/var/lib/machines" = {
      device = "/dev/disk/by-uuid/11cd85fd-8feb-4d09-96c6-a822676d1124";
      fsType = "btrfs";
      options = ["compress-force=zstd" "noatime" "subvol=@/machines"];
    };

    "/var/lib/portables" = {
      device = "/dev/disk/by-uuid/11cd85fd-8feb-4d09-96c6-a822676d1124";
      fsType = "btrfs";
      options = ["compress-force=zstd" "noatime" "subvol=@/portables"];
    };

    "/var/log" = {
      device = "/dev/disk/by-uuid/11cd85fd-8feb-4d09-96c6-a822676d1124";
      fsType = "btrfs";
      options = ["compress-force=zstd" "noatime" "subvol=@/log"];
    };

    "/home/javier" = {
      device = "/dev/disk/by-uuid/29793c48-c1d1-4e91-9671-8450734d6dfa";
      fsType = "btrfs";
      options = ["compress-force=zstd"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/288E-C4C9";
      fsType = "vfat";
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option  but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
